app/views/blog.py
from flask import render_template, flash, redirect, url_for, request, g, Blueprint, abort
from flask.ext.login import login_required, current_user
from datetime import datetime
from app import db
from app.models import Post, User
from app.forms import CKTextAreaField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask.ext.admin import AdminIndexView, BaseView
from flask_admin.contrib.sqla import ModelView
from flask_admin.contrib.fileadmin import FileAdmin
from config import USER_ROLES, basedir
from sqlalchemy import desc
import os

blog = Blueprint('blog', __name__, subdomain='blog', static_folder="../static")

def is_admin():
    if g.user.role == 1:
        return True
    else:
        return False

@blog.before_request
def before_request():
    g.user = current_user
    if g.user.is_authenticated:
        g.user.last_seen = datetime.utcnow()
        db.session.add(g.user)
        db.session.commit()

@blog.route('/')
@blog.route('/index')
def index():
    posts = Post.query.filter_by(draft=False).order_by(Post.id.desc()).all()
    return render_template('blog/index.html', posts=posts)

@blog.route('/post/<num>')
def post(num):
    post = Post.query.filter_by(id=num).first()
    if post is None:
        return render_template('404.html'), 404
    return render_template('blog/single_post.html', post=post)

class ProtectedBaseView(BaseView):
    def is_accessible(self):
        if current_user.is_authenticated and current_user.role == 1:
            return True
        return False

    def _handle_view(self, name, **kwargs):
            if not self.is_accessible():
                flash("You don't have permission to go there", category="warning")
                return redirect(url_for('main.index'))

class ProtectedIndexView(AdminIndexView, ProtectedBaseView):
    pass

class ProtectedModelView(ModelView, ProtectedBaseView):
    pass

class ProtectedFileAdmin(FileAdmin, ProtectedBaseView):
    pass

class PostModelView(ProtectedModelView):
    edit_template = 'blog/admin/edit_add_post.html'
    create_template = 'blog/admin/edit_add_post.html'
    form_overrides = dict(body=CKTextAreaField)
    column_formatters=dict(body=lambda view, context, model, name: ' '.join(model.body.split(" ")[:50]))
    column_default_sort = ('id', True)
    form_args = dict(
        author=dict(
            default=User.query.filter_by(role=USER_ROLES['admin']).first(),
            query_factory=lambda: [current_user]
        ))

    def __init__(self):
        super(PostModelView, self).__init__(Post, db.session)

@blog.route("/admin/imageselect", methods=['GET','POST'])
@login_required
def imageselect():
    if not is_admin():
        abort(404)
    files = os.listdir(os.path.join(basedir, 'app/static/bloguploads'))
    files = [ (f, os.path.join('/static/bloguploads', f)) for f in files ]
    return render_template("blog/imageselect.html",
                           title="Select image",
                           files=files[:100], #perhaps make pages instead
                           cknum=request.args['CKEditorFuncNum'])

app/views/irsec.py
from flask import render_template, flash, redirect, session, url_for, request, g, abort, Blueprint
from app import app, db

irsec = Blueprint('irsec', __name__, subdomain='irsec', static_folder="../static")

@irsec.route('/')
@irsec.route('/index')
def index():
    return render_template('irsec/index.html', title="Home")

@irsec.route('/signup')
def signup():
    return render_template('irsec/signup.html', title="Signup")

@irsec.route('/about')
def about():
    return render_template('irsec/about.html', title="About")

@irsec.errorhandler(404)
def not_found_error(error):
    return render_template('irsec/404.html')

app/templates/blog/base.html
<!doctype html>
<html>
    <head>
 
        {% if title %}
 
        <title>{{title}}</title>
 
        {% else %}
 
            <title>RC3 Blog</title>
 
        {% endif %}
 
        <meta charset="UTF-8">
        <link rel="icon" href="/static/img/favicon.ico">
        <script src="/static/js/vendor/modernizr.js"></script>
        <link href="/static/css/normalize.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
        <link href="/static/css/foundation.css" rel="stylesheet">
        <link href="/static/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet" href="/static/foundation-icons/foundation-icons.css">
        <link href="/static/css/style.css" rel="stylesheet">
        <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-54644206-2', 'auto');
    ga('send', 'pageview'); </script> <!-- I'm sorry, they just make  it so easy ;_; -->
    </head>
 
    <body>
        <nav class="top-bar" data-topbar >
 
            <ul class="title-area">

                <li class="name">
                    <h1>
                        <a href="#" class="has-dropdown" data-dropdown="site-nav"><img height="56" width="56" src="/static/img/logo.png"></a>

                    </h1>
                    <ul id="site-nav" class="foundationGrey f-dropdown" data-dropdown-content>
                        <li class="row"><a href="{{url_for('main.index')}}" class="greyText">Main</a></li>
                        <li class="row"><a href="{{url_for('irsec.index')}}" class="greyText">IRSeC</a></li>
                        <li class="row"><a href="{{url_for('blog.index')}}" class="greyText">Blog</a></li>
                    </ul>

                </li>

            </ul>

            <section class="top-bar-section">

                <ul class="left">

                    <li class="divider"></li>
                        <li><a href="{{ url_for('.index') }}"><i class="fa fa-home"></i></a></li>
                    <li class="divider"></li>
                    {% if g.user.is_authenticated and g.user.role %}
                    <li class="divider"></li>
                    <li><a href="{{ url_for('admin.index') }}"><i class="fa fi-wrench"></i> Admin</a></li>
                    <li class="divider"></li>
                    {% endif %}
                </ul>

            </section>
        </nav>
        <div class="row">
        <div class="small-12 columns">
                
                {% with messages = get_flashed_messages() %}
 
                {% if messages %}
 
                    {% for message in messages %}
 
                    <div data-alert class="alert-box info radius"> {{message}} <a href="" class="close">&times;</a> </div>
                    
                    {% endfor %}
 
                {% endif %}
 
                {% endwith %}
        </div>
        </div>
        <div class="row">
        <div class="small-12 columns">
 
                {% block content %}
 
                {% endblock %}
 
        </div>
        </div>

    </body>
    <footer>
        <script src="/static/js/vendor/fastclick.js"></script>
        <script src="/static/js/vendor/modernizr.js"></script>
        <script src="/static/js/vendor/jquery.js"></script>
        <script src="/static/js/foundation/foundation.min.js"></script>
        <script>
          $(document).foundation();
        </script>
    </footer>
</html>

app/templates/blog/imageselect.html
<html>
    <head>
        <link href="/static/css/foundation.css" rel="stylesheet">
        <link href="/static/css/style.css" rel="stylesheet">
        <link rel="stylesheet" href="/static/foundation-icons/foundation-icons.css">
    </head>
    <body>
        <div id="imgform" class="row">
            <form>
                <ul class="small-block-grid-5 center">
            {% for name, link in files %}
            <li>
                <div class="row">
                    <img class="imgselect" src="{{link}}" title="{{name}}">
                </div>
                <div class="row">
                    <input type="radio" name="selectedfile" id="selectedfile" value="{{link}}">
                </div>
            </li>
            {% endfor %}
            </ul>
            <input class="button" type="submit" value="Submit">
            </form>
        </div>
    </body>
    <footer>
        <script src="/static/js/vendor/jquery.js"></script>
        <script src="//cdn.ckeditor.com/4.4.7/full/ckeditor.js"></script>
        <script src="/static/js/foundation/foundation.min.js"></script>
        <script>
            $(document).foundation();
            $('#imgform').on('submit', function () {
                var fileUrl = document.forms[0].selectedfile.value
                var funcNum = {{cknum}};
                window.opener.CKEDITOR.tools.callFunction( funcNum, fileUrl );
                close();
            });
        </script>
    </footer>
</html>

app/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
<div class="row">
    <h1>RC3 Blog</h1>
</div>
{% for post in posts %}
<div class="row pad">
<div class="row panel">
    <div class="row">
        <div class="small-12 columns">
            <h1 class="left">{{post.title}}</h1>
        </div>
    </div>
    <div class="row">
        <div class="small-1 columns">
            <img src="{{post.author.avatar(46)}}">
        </div>
        <div class="small-2 columns left">
            <div class="row">
                {{post.author.nickname}}
            </div>
            <div class="row">
                <em>{{post.timestamp.strftime('%B %d, %Y')}}</em>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns bt-pad">
            {{post.body | safe}}
        </div>
    </div>
</div>
</div>
{% endfor %}
{% endblock %}

app/templates/blog/single_post.html
{% extends "blog/base.html" %}

{% block content %}
<div class="row pad">
<div class="row panel">
    <h1 class="left">{{post.title}}</h1>
    <div class="row">
        <div class="small-12 columns">
            {{post.body | safe}}
        </div>
    </div>
</div>
</div>
{% endblock %}