app/views/main.py
"""
main.py - The main view fuction for the website. This defines each "route" and
what should happen when a user visits the page.
"""
from datetime import datetime
from flask import render_template, flash, redirect, session, url_for, request, g, abort, Blueprint
from flask.ext.login import login_user, logout_user, current_user, login_required
from app import db, lm, google
from app.models import *
from app.emails import contact_us, send_newsletter
from config import USER_ROLES
from sqlalchemy import desc
from random import randint
from app.forms import *

#defines the main path for the application
main = Blueprint('main', __name__)

def is_admin():
    if g.user.role == USER_ROLES['admin']:
        return True
    return False

def sort_user_scores(l, semester):
    '''Sorts users by score for the scoreboard
    args:
        l - the input list of users to be sorted
        semester - the semester to get the score for
    Note: does not return, modifies the original list
    '''
    for i in xrange(1, len(l)):
        j = i-1
        key = l[i]
        while (l[j].get_score(semester=semester) < key.get_score(semester=semester)) \
                and (j >= 0):
            l[j+1] = l[j]
            j -= 1
        l[j+1] = key

#look in the wiki for documentation on these decorators
@main.before_request
def before_request():
    '''Runs before every request to get information to be used in the
    rendered pages
    Gets the user object, current semester object, and semester list
    Also updates the user's last seen time
    '''
    g.user = current_user
    g.csemester = Semester.query.filter_by(current=True).first()
    g.route = request.path
    g.semesters = Semester.query.order_by(desc('id')).all()
    if "semester" not in session.keys() or session['semester'] \
            not in [ i.lname for i in g.semesters ]:
        session['semester'] = g.csemester.lname
    g.semester = session['semester']
    if g.user.is_authenticated:
        g.user.last_seen = datetime.utcnow()
        db.session.add(g.user)
        db.session.commit()

@main.route('/')
@main.route('/index')
def index():
    '''The default page of the app
    Returns: The rendered homepage or th page in the 'next' get parameter
    '''
    if request.args.get('next'):
        return redirect(url_for(request.args.get('next')))
    usern = g.user
    browser = request.user_agent.browser
    if browser == "firefox":
        flash("Firefox often doesn't play nice with Google OAuth. \
              You may want to try chrome if it won't let you login")

    #only show the user if they are not an admin
    all_users = [ user for user in
                 User.query.filter(User.role != USER_ROLES['admin']).all()
                 if user.get_score(semester=g.csemester) ]
    sort_user_scores(all_users, semester=g.csemester)

    return render_template("index.html",
                           title='Home',
                           user=usern,
                           topusers=all_users[:5],
                           semester=g.csemester)

@lm.user_loader
def load_user(id):
    '''Gets the current user object from the user id
    arg:
        id - the current user's id from the database
    Returns: the user object
    '''
    return User.query.get(int(id))

@main.route('/logout')
@login_required
def logout():
    '''The user logout page
    Returns: A redirect for the index page, after clearing the session
    '''
    logout_user()
    session.clear()
    return redirect(url_for('.index'))

@main.route('/login/authorized')
@google.authorized_handler
def authorized(response):
    '''Handles the OAuth response from Google
    Returns: a redirect to the index page, after logging the user in (or erroring)
    '''
    if response is None:
        flash('Login failed :(')
        return redirect(url_for('main.index'))

    session['google_token'] = (response['access_token'], '')
    me = google.get('userinfo')

    #is the user either from RIT or explicitly allowed?
    alloweduser = AllowedUser.query.filter_by(email=me.data['email'], ban=False).first()
    if me.data['hd'] != "g.rit.edu" and alloweduser is None:
        me = None
        response = None
        logout_user()
        session.clear()
        flash('You must log in with your RIT Email \
              or obtain special permission to log in from an administrator')
        return redirect(url_for('main.index'))

    #get the existing user, or create a new one
    user = User.query.filter_by(email=me.data['email']).first()
    if user is None:
        if me.data['name']:
            nickname = me.data['name']
        elif me.data['given_name']:
            nickname = me.data['given_name']
        else:
            #Use everything up to @ for username (RIT ID)
            nickname = me.data['email'].split('@')[0][:10]
        #if the email address > 10 digits truncate
        username = me.data['email'].split('@')[0][:10]
        #if the username already exists mainend a random integer to the end
        while User.query.filter_by(username=username).first() is not None:
            username = username[:7] + str(randint(100, 999))
        user = User(nickname=nickname,
                    username=username,
                    email=me.data['email'],
                    role=USER_ROLES['user'])
        db.session.add(user)
        db.session.commit()
    if me.data['name'] and user.nickname is not me.data['name']:
        user.nickname = me.data['name']
        db.session.add(user)
        db.session.commit()
    elif me.data['given_name'] and user.nickname is not me.data['name']:
        user.nickname = me.data['given_name']
        db.session.add(user)
        db.session.commit()
    login_user(user, remember = False)
    return redirect(request.args.get('next') or url_for('main.index'))

@main.route('/user/<username>')
@login_required
def user(username):
    '''Profile page for a user
    arg:
        username - the name of the user
    Returns: the rendered profile page for the user
    '''
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User not found.')
        abort(404)
    return render_template('user.html', title=user.nickname, user=user)

@main.route('/resources')
@login_required
def resources():
    '''The presentations section of the site
    Returns: the rendered resources page for the selected semester
    '''
    sem = Semester.query.filter_by(lname=session['semester']).first()
    if sem is None:
        return render_template('404.html', title='404'), 404
    pres = [ p for p in Presentation.query.order_by('week') if p.semester.lname == sem.lname ]
    return render_template('resources.html',
                           title='Resources',
                           pres_list=pres,
                           semester=sem)

@main.route('/edit', methods = ['GET', 'POST'])
@login_required
def edit():
    '''Allows editing a user's profile
    Returns: The profile editing page or the user's profile page when the edit
             is committed
    '''
    form = EditForm()
    if form.validate_on_submit():
        g.user.about_me = form.about_me.data
        g.user.major = form.major.data
        if form.newsletter.data:
            g.user.newsletter = 1
        else:
            g.user.newsletter = 0
        db.session.add(g.user)
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.user', username=g.user.username))
    else:
        form.about_me.data = g.user.about_me
        form.major.data = g.user.major
        if g.user.newsletter == 1:
            form.newsletter.data = True
        else:
            form.newsletter.data = False
    return render_template('edit.html', title='Edit', form=form, user=g.user)

@main.route('/email', methods=['POST'])
def email():
    '''Sends an email to the rc3 admins
    Returns: a redirect for the contact us page after the email has been sent
    Note: Not implemented yet... perhaps not needed at all
    '''
    # Check post values
    if False:
        flash('Sorry, please try to send your message again')
        return redirect(url_for('main.contact'))
    # Spawn new process to send email
    flash('Your message has been sent!')
    return redirect(url_for('main.contact'))

@main.route('/scoreboard')
def scoreboard():
    '''The semester scoreboard page
    Returns: the rendered scoreboard page for the selected semester
    '''
    sem = Semester.query.filter_by(lname=session['semester']).first()
    if sem is None:
        return render_template('404.html', title='404'), 404
    all_users = [ user for user in User.query.all()
                 if user.role != USER_ROLES['admin'] and user.get_score(semester=sem) ]
    sort_user_scores(all_users, semester=sem)
    return render_template('scoreboard.html',
                           title='Scoreboard',
                           users=all_users,
                           semester=sem)

@main.route('/halloffame')
def halloffame():
    '''The scoreboard page for top all time scores across semesters
    Returns: the rendered hall of fame page
    '''
    users = [ user for user in User.query.all() if user.get_score() ]
    users = sorted(users, reverse=True)
    return render_template('halloffame.html', users=users[:10])

@main.route('/contact', methods=['GET', 'POST'])
def contact():
    '''The page for contacting the RC3 admins
    Returns: the rendered contact page
    '''
    form = ContactUs()
    if form.validate_on_submit():
        subject = "{0} has sent the RC3 Admins a Message".format(form.name.data)
        message = render_template('contact_us_message.html',
                                  recp=form.email.data,
                                  name=form.name.data,
                                  msg=form.body.data)
        email = [subject, message]
        contact_us(email)
        flash('Your message has been sent!')
        return redirect(url_for('main.contact'))

app/templates/about.html
{% extends "base.html" %}
 
{% block content %}
<div class="row">
<div class="small-8 columns left">

            <h3>About RC3</h3>
            
            <div class="panel">
            <a href="#" class="th bot-marg"><img src="/static/img/rc3.jpg" width="1000" alt=""></a>
            
            <p>RIT Competitive Cybersecurity Club (RC3) is a student-run organization dedicated to educating and preparing RIT students to compete in security-related competitions, as well showcase RIT student talent in the world of security today. Whether you're new to competitive cybersecurity or a veteran, RC3 has a place for you.</p>

            <p>RC3 centers around live individual and team-based security exercises covering a wide variety of areas in computing security, including penetration testing, windows and linux server hardening, web security, network services, and more. Throughout the semester students engage in security challenges to test their skills and knowledge.</p>
            
            <p>We spend the first thirty minutes discussing news and current events in the security industry, and then present on a topic for 30-40 minutes. After the presentation we spend about
            an hour doing a hands on demo with a competitive element. We encourage you to ask questions and you're welcome to go at your own pace.</p>

            <p>Regularly scheduled meetings are held Fridays at 12 pm in 70-2410, the security lab.</p>
            </div>
 </div>
 <div class="small-4 columns right">
    <h3>RC3 TL;DR</h3>
     <div class="row panel">
        <div class="small-6 columns">
            <h4>Who</h4>
        </div>
        <div class="small-10 columns panel">
            We're open to all majors. 
        </div>
        <div class="small-6 columns">
            <h4>What</h4>
        </div>
        <div class="small-10 columns panel">
            Hands on computer security.
        </div>
        <div class="small-6 columns">
            <h4>When</h4>
        </div>
        <div class="small-10 columns panel left">
            Every Friday 12-2.
        </div>
        <div class="small-6 columns">
            <h4>Where</h4>
        </div>
        <div class="small-10 columns panel">
            GOL(70)-2410
        </div>
        <div class="small-6 columns">
            <h4>Why</h4>
        </div>
        <idv class="small-10 columns panel left">
            Breaking stuff is fun.
        </div>
    </div>
 </div>

<div class="columns small-12 positions">
<h2>RC3 Executive Board</h2>
    <div class="row panel">
        <div class="small-3 columns">
            <strong>President:</strong>
        </div>
        <div class="small-3 columns">
            Ben Bornholm
        </div>
        <div class="small-3 columns">
            <strong>Vice President:</strong>
        </div>
        <div class="small-3 columns">
            Nick Piazza
        </div>
    </div>
    <div class="row panel">
        <div class="small-3 columns">
            <strong>Competition Architect:</strong>
        </div>
        <div class="small-3 columns">
            Sarah Jacobus
        </div>
        <div class="small-3 columns">
            <strong>Tech Lead:</strong>
        </div>
        <div class="small-3 columns">
            Brad Campbell
        </div>
    </div>
    <div class="row panel">
        <div class="small-3 columns">
            <strong>Webmaster:</strong>
        </div>
        <div class="small-3 columns">
            Jaime Geiger
        </div>
        <div class="small-3 columns">
            <strong>Treasurer:</strong>
        </div>
        <div class="small-3 columns">
            Mike Milkovich
        </div>
    </div>
    <div class="row panel">
        <div class="small-3 columns">
            <strong>Secretary:</strong>
        </div>
        <div class="small-3 columns">
            Kristen Tumacder
        </div>
        <div class="small-6">
    </div>
 </div>
{% endblock %}

app/templates/admin.html
<!-- extend base layout -->
{% extends "base.html" %}
 
{% block content %}
<script src="//cdn.ckeditor.com/4.5.1/full/ckeditor.js"></script>
<div class="row admin-info">
        <h2>Admin Stuff</h2>
            <dl class="tabs radius" data-tab>
                <dd class="tab-title active"><a href="#panel2-1">Send Newsletter</a></dd>
                <dd class="tab-title"><a href="#panel2-2">Create Challenge</a></dd>
                <dd class="tab-title"><a href="#panel2-3">Update Score</a></dd>
                <dd class="tab-title"><a href="#panel2-4">User Permissions</a></dd>
                <dd class="tab-title"><a href="#panel2-5">Add Subscriber</a></dd>
                <dd class="tab-title"><a href="#panel2-6">Manage Presentations</a></dd>
            </dl>
            <div class="tabs-content">
                <div class="content active" id="panel2-1">
                    <p>{% include "admin/send_newsletter.html" %}</p>
                </div>
                <div class="content" id="panel2-2">
                    <p>{% include "admin/create_challenge.html" %}</p>
                </div>
                <div class="content" id="panel2-3">
                    <p>{% include "admin/update_score.html" %}</p>
                </div>
                <div class="content" id="panel2-4">
                    <p>{% include "admin/permissions.html" %}</p>
                </div>
                <div class="content" id="panel2-5">
                    <p>{% include "admin/add_subscriber.html" %}</p>
                </div>
                <div class="content" id="panel2-6">
                    <p>{% include "admin/manage_presentations.html" %}</p>
                </div>
</div>


{% endblock %}

app/templates/challenges.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-center">{{semester.name}} Challenges</h2>

{% if not challenges.count() %}
<h4 class="text-center">Nothing here yet. Check back soon!</h4>
{% endif %}

<div class="small-12 columns">
{% set i = 0 %}
{% for challenge in challenges %}
        <div class="row panel">
            <div class="small-4 medium-4 columns"><a href="{{ url_for('main.challenge', chall = challenge.name, semester=semester.lname)}}">{{challenge.name}}</a></div>
            <div class="small-3 medium-6 columns">{{ challenge.about|truncate(60) }}</div>
            <div class="small-2 medium-2 columns"><a href="#" data-dropdown="hover{{i}}" data-options="is_hover:true">{{challenge.total_users()}} Participants</a></div>
            {% if challenge.total_users() > 0 %}
                <ul id="hover{{i}}" class="f-dropdown" data-dropdown-content>
                {% set users = challenge.get_users() %}
                {% for user in users %}
                    <li><a href="{{ url_for('main.user', username = user.username)}}">{{user.nickname}}</a></li>
                {% endfor %}
                </ul>
            {% endif %}
 
        </div>
      {% set i = i+1 %}
{% endfor %}
</div>
{% endblock %}

app/templates/contact.html
{% extends "base.html" %}
 
{% block content %}
 
 <h3>Contact Us</h3>

 <form action="" method="POST" name="contact">
 	{{form.hidden_tag()}}
 	<div class="large-6 columns panel">
	 	<div class="row">
	 		<div class="large-8 columns">
	 			<label>Your Name:* {% for error in form.errors.name %}<span style="color: red;">This field is required</span>{% endfor %}
					{{form.name}}
	 			</label>
	 		</div>
	 	</div>
	 	<div class="row">
	 		<div class="large-8 columns">
	 			<label>Your Email:* {% for error in form.errors.email %}<span style="color: red;">This field is required</span>{% endfor %}
					{{form.email}}
	 			</label>
	 		</div>
	 	</div>
	 	<div class="row">
	 		<div class="large-10 columns">
	 			<label>Your Message:* {% for error in form.errors.body %}<span style="color: red;">This field is required</span>{% endfor %}
					{{form.body(rows = 5)}}
	 			</label>
	 		</div>
	 	</div>
	 	<p><input type="submit" class="button" value="Submit"></p>
 	</div>
 </form>
 
{% endblock %}

app/templates/ctf.html
<!-- extend base layout -->
{% extends "base.html" %}
 
{% block content %}

<h2 class="text-center">2014 RC3 CTF</h2>

{% endblock %}

app/templates/edit.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
<h1>Edit Your Profile</h1>
<form action="" method="POST" name="edit">
	{{form.hidden_tag()}}
	<div class="large-6">
		<div class="row panel">
			<div class="small-6 medium-3">
				Your major:
			</div>
			<div class="small-3 medium-3">
				{{form.major}}
			</div>
			<div class="small-6 medium-3">
				About Yourself:
			</div>
			<div class="small-12 medium-12">
				{{form.about_me(rows = 4)}}
			</div>
			<div class="small-6 medium-6">
				Get Email Updates:  {{form.newsletter}}
			</div>
			<div class="small-3 medium-3">
				
			</div>
			<input type="submit" class="button" value="Save Changes">
			<a href="{{ url_for('main.user', username = user.username )}}" class="button">Back to Profile</a>
		</div>
	</div>
</form>
{% endblock %}

app/templates/edit_challenge.html
<!-- extend base layout -->
{% extends "base.html" %}
{% block content %}

<h2>Edit Challenge</h2>
<form action="" method="POST" name="edit_challenge">
    {{form.hidden_tag()}}
    <div class="small-6 columns">
        <div class="row panel">
            <div class="small-8">
                Challenge Name:
            </div>
            <div class="small-8">
                {{form.name}}
                {% for error in form.errors.name %}
                <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div class="small-6 medium-3">
                Date:
            </div>
            <div class="small-3 medium-3">
                {{form.date}}
            </div>
            <div class="small-6 medium-3">
                About:
            </div>
            <div class="small-12 medium-12">
                {{form.about(rows = 8)}}
            </div>
            <div class="small-3 medium-3">
 
            </div>
            <input type="submit" class="button" value="Save Changes">
            <a href="{{ url_for('main.challenge', chall = challenge.name, semester=challenge.semester.lname)}}" class="button">Back to Challenge</a>
        </div>
    </div>
</form>

{% endblock %}

app/templates/generate_scoreboard.html
<div class="small-12">

    <table>

        <tbody>
            {% if users %}
            {% for user in users %}
                <tr valign="center">
                    <td><a href="{{ url_for('main.user', username = user.username )}}"><img src="{{user.avatar(30)}}"></a></td>
                    <td><a href="{{ url_for('main.user', username = user.username )}}">{{user.nickname}}</a>
                        {% if user.is_admin() %}  <a href="#" title="{{user.nickname}} is an admin"><i class="fa fa-star"></i></a>{% endif %}
                    </td>
                    {% if challenge %}
                        <td>{{user.get_score(challenge=challenge, semester=challenge.semester)}}</td>
                    {% elif semester %}
                        <td>{{user.get_score(semester=semester)}}</td>
                    {% else %}
                        <td>{{user.get_score()}}</td>
                    {% endif %}
                </tr>
            {% endfor %}
            {% endif %}
        </tbody>

    </table>

</div>

app/templates/history.html
        <div class="small-12 panel left">

            <div class="small-1 columns hide-for-small"><img src="{{score.user.avatar(50)}}" class="th"></div>
            <div class="small-10 columns left"><strong>Participated in <a href="{{ url_for('main.challenge', chall = score.challenge.name, semester=score.challenge.semester.lname)}}"> {{score.challenge.name}} ({{score.challenge.semester.name}})</a></strong></div>
            {%	if score.points > 0 %}
            <a href="javascript:void(0)" class="left small-2 medium-1"><span class="score">+ {{score.points}}</span></a>
            {% endif %}

        </div>

app/templates/post.html
<p class="label left">{{post.author.nickname}}</p>

        <div class="small-12 panel left">

            <div class="small-2 columns"><img src="{{post.author.avatar(50)}}" class="th"></div>
            <div class="small-10 columns">{{post.body}}</div>

        </div>

app/templates/resources.html
{% extends "base.html" %}
{% block content %}

<h2 class="text-center">{{semester.name}} Resources</h2>

{% if not pres_list %}
<h4 class="text-center">Nothing here yet. Check back soon!</h4>
{% endif %}

{% set i=0 %}
<ul class="accordion" data-accordion>
{% if pres_list %}
{% for pres in pres_list %}
    <li class="accordion-navigation">
    <a href="#panel{{i}}">
    <h2> <strong>Week {{pres.week}}</strong> - {{pres.name}}</h2>
    </a>

    <div id="panel{{i}}" class="content">
    <iframe src="{{pres.link}}" frameborder="1" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
    </div>

    </li>
{% set i = i+1 %}
{% endfor %}
{% endif %}
</ul>

</br>
</br>
{% endblock %}

app/templates/test.html
<!-- extend base layout -->
{% extends "base.html" %}
 
{% block content %}

<ul class="tabs" data-tab role="tablist">
  <li class="tab-title active" role="presentational" ><a href="#panel2-1" role="tab" tabindex="0" aria-selected="true" controls="panel2-1">Tab 1</a></li>
  <li class="tab-title" role="presentational" ><a href="#panel2-2" role="tab" tabindex="0"aria-selected="false" controls="panel2-2">Tab 2</a></li>
  <li class="tab-title" role="presentational"><a href="#panel2-3" role="tab" tabindex="0" aria-selected="false" controls="panel2-3">Tab 3</a></li>
  <li class="tab-title" role="presentational" ><a href="#panel2-4" role="tab" tabindex="0" aria-selected="false" controls="panel2-4">Tab 4</a></li>
</ul>
<div class="tabs-content">
  <section role="tabpanel" aria-hidden="false" class="content active" id="panel2-1">
    <h2>First panel content goes here...</h2>
  </section>
  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-2">
    <h2>Second panel content goes here...</h2>
  </section>
  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-3">
    <h2>Third panel content goes here...</h2>
  </section>
  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-4">
    <h2>Fourth panel content goes here...</h2>
  </section>
</div>

<a href="#" data-dropdown="drop1">Has Dropdown</a>
<ul id="drop1" class="f-dropdown" data-dropdown-content>
  <li><a href="#">This is a link</a></li>
  <li><a href="#">This is another</a></li>
  <li><a href="#">Yet another</a></li>
</ul>
<a href="#" data-dropdown="drop2">Has Content Dropdown</a>
<div id="drop2" data-dropdown-content class="f-dropdown content">
  <p>Some text that people will think is awesome! Some text that people will think is awesome! Some text that people will think is awesome!</p>
</div>

{% endblock %}

app/templates/user.html
<!-- extend base layout -->
{% extends "base.html" %}
 
{% block content %}

<div class="row radius panel account-info">
 
    <div class="small-12 medium-6 large-4 columns">
 
        <img class="th" src="{{user.avatar(128)}}" alt="{{user.nickname}}">
        {% if user.id == g.user.id %} 
            <div class="small-12 columns">
                <span data-tooltip aria-haspopup="true" class="has-tip" title="Sign up on gravatar.com using {{user.email}} and your picture will show up here">
                How do I change my avatar?
                </span>
 
            </div>
        {% endif %}
    </div>



    <div class="small-12 medium-6 large-8 columns">
 
        <div class="row">
            <div class="small-12 columns">
                <h3> {{user.nickname}}
                    {% if user.is_admin() %}  <a href="#" title="{{user.nickname}} is an admin"><i class="fa fa-star"></i></a>{% endif %}
                    <em class="text-small"> [ {{user.username}} ]</em>
                </h3>
            </div>

            <div class="small-12 columns">
            </div>
            <div class="small-12 columns">
            {% if user.about_me %}<div class="about-info small-12 columns" data-equalizer-watch>{{user.about_me}}</div>{% endif %}
            </div>
            <div class="small-12 columns">
                {% if user.get_score(semester=g.csemester) %}<span class="score"> {{user.get_score(semester=g.csemester)}} Points</span>{% endif %}
            {% if user.get_score() %}<span class="score"> {{user.get_score()}} Overall</span>{% endif %}
            </div>
        </div>
        <div class="row">
            {% if user.id == g.user.id %} <div class="small-3 columns"><a class="button tiny success submit" href="{{url_for('main.edit')}}">EDIT</a></div>{% endif %}
        </div>
    </div>
    {{user.pic}}
    {% if user.last_seen %}<div class="small-9 columns small-text-right"><em class="smaller-text">Last login on {{user.last_seen_print()}}</em></div>{% endif %}
</div>
 
{% for score in user.scores[::-1] %}
 
 {% include 'history.html' %}
 
{% endfor %}
 
{% endblock %}

app/templates/welcome_email.html
<div class="panel"></div>
<p>Hi {{user.nickname}}!</p>
<br>
<p>Welcome to RC3! Thanks for signing up. Each week we'll send you a little heads up about what we did last week and what's in store for this week. As a reminder, we meet Fridays from 12pm-2pm in 70-2410, the security lab.</p>
<br>
<p>I look forward to seeing you at RC3!</p>
<br>
<p>Jon Barber <br>	
{{url_for('main.index', _external = True)}} <br>
RC3 President <br>
SPARSA Vice President of Research <br></p>
<br>
<br>
<br>
</div>
 If you don't like emails, feel free to unsubscribe at {{url_for('main.unsubscribe', _external = True)}}